name: lidom-live-minute

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/5 * * * *"   # GitHub ejecuta como mínimo cada ~5 min (UTC)

permissions:
  contents: write

concurrency:
  group: lidom-live-minute
  cancel-in-progress: true

env:
  TZ: America/Santo_Domingo
  SOURCE_HOME: https://pelotainvernal.com/
  DETAILS_FETCH: recent
  DETAILS_DAYS: "14"
  DETAILS_CONCURRENCY: "4"
  DETAILS_STATUSES: "2,4,5,6"   # LIVE, DELAYED, SUSPENDED, FINAL

jobs:
  live_tick_loop:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Re-auth remote with token
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Configure git
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Minute loop (5 ticks de 60s)
        shell: bash
        run: |
          set -euo pipefail
          ticks=5
          for i in $(seq 1 $ticks); do
            echo "== Tick $i/$ticks =="
            node scraper.mjs || true

            # Valida archivos si existen
            if [ -f docs/live.json ]; then jq . docs/live.json > /dev/null || true; fi
            if [ -f docs/latest.json ]; then jq . docs/latest.json > /dev/null || true; fi

            # Commit/push solo si hubo cambios en docs/
            if ! git diff --quiet -- docs/; then
              git add docs/
              TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
              git commit -m "chore: live minute tick ${TS} [skip ci]"
              git pull --rebase origin main || true
              git push origin HEAD:main
            else
              echo "No changes to commit (tick $i)."
            fi

            # Si no hay juegos live, salimos antes de tiempo
            if [ -f docs/live.json ] && jq -e '.live | length == 0' docs/live.json > /dev/null 2>&1; then
              echo "No hay juegos en vivo; fin temprano."
              break
            fi

            # Dormimos 60s a menos que sea el último tick
            if [ "$i" -lt "$ticks" ]; then
              sleep 60
            fi
          done
